MODEL:
  NAME: resnet50
DATA:
  NUM_INSTANCES: 4
  TRAIN_BATCH: 32
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  PAIR_LOSS: triplet
  CAL: cal
  PAIR_M: 0.3
  PAIR_LOSS_WEIGHT: 1.0
TAG: res50-cels-cal-tri-16x4