import os.path

UNDETECTED_FACE = '-00001'
PRCC_TEST_PATH = os.path.join("rgb", "test")
CCVID = 'ccvid'
PRCC = 'prcc'
LTCC = 'ltcc'
LAST = 'last'
VCCLOTHES = 'vcclothes'
VCCLOTHES_SC = 'vcclothes_sc'
VCCLOTHES_CC = 'vcclothes_cc'
DATASETS = [CCVID, PRCC, LTCC, LAST, VCCLOTHES, VCCLOTHES_SC, VCCLOTHES_CC]
CAL_DATALOADER = 'CAL_DATALOADER'
FACE_DATALOADER = 'FACE_DATALODAER'